@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "com.example.travelingsalsemendemonstrator.controller.RestController#deleteScenario(String)",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "com.example.travelingsalsemendemonstrator.controller.RestController",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_1322970774 { 
   	label=example
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1453431066 { 
   	label=travelingsalsemendemonstrator
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_1022327817 { 
   	label=ScenarioController
	labeljust=l
	fillcolor=white
	style=filled
   
   ScenarioController595464079XXXdeleteScenario1808118735[
	label="+ deleteScenario()"
	style=filled
	fillcolor=white
	tooltip="ScenarioController

&#10;  A Function to delete a given scenario form the Local System&#10; &#10;  @param id The filename of the file one wants to delete.&#10;  @return true if deleted successfully, false if the deletion failed.&#10; "
	fontcolor=darkgreen
];
} 

subgraph cluster_466958899 { 
   	label=RestController
	labeljust=l
	fillcolor=white
	style=filled
   
   RestController595464079XXXdeleteScenario1808118735[
	label="+ deleteScenario()"
	style=filled
	fillcolor=white
	tooltip="RestController

&#10;  Endpoint to delete a preselected Scenario&#10;  @param scenarioName the filename of the scenario you want to delete&#10;  @return a ResponseEntity of type boolean with http-status 200 in case the scenario was deleted sucessfully,&#10;  otherwise http-status 500&#10; "
	penwidth=4
	fontcolor=darkgreen
];
} 
} 
} 

'edges    
RestController595464079XXXdeleteScenario1808118735 -> ScenarioController595464079XXXdeleteScenario1808118735;
    
}
@enduml